### ISSUE TITLE
failed to create kubernetes rest client for update of resource: resource [v1/ServiceAccount] isn't valid for cluster

### ISSUE THREAD

**Issue by jouros** [kube-champ/terraform-k8s-flux-bootstrap#1]
I'm getting these errors for every flux manifest there is. This is related to kubectl, but I can't find a workaround go get this module working, kubectl does not install any of manifests. I had similar errors with terraform flux provider example also. Kube is 1.19 and versions.tf:
terraform {
  required_version = ">=0.15"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.3.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "= 1.11.1"
    }
    flux = {
      source  = "fluxcd/flux"
      version = "0.1.9"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.1.2"
    }
  }
}

Namespace flux-system gets created as expected. What kubernetes and provider versions you have tested with this module?

**Comment by IbraheemAlSaady** [comment]
Hello @jouros, 

I have just tested the module with the [basic](https://github.com/kube-champ/terraform-k8s-flux-bootstrap/tree/master/examples/basic) profile from the `examples` and it ran and was deployed successfully. I've also tested it with the `versions.tf` you've provided and was deployed successfully.

These are the versions I've been testing with.

```
Terraform: 0.15.5
Kubernetes: 1.19.0
```

Would you mind sharing your full HCL and also any errors that you've encountered?

**Comment by jouros** [comment]
I had similar errors with fluxcd/flux provider install example. terraform plan is ok and I can create flux-system namespace with terraform module and also destroy ok. 

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.flux.kubernetes_namespace.flux_system: Creating...
module.flux.kubernetes_namespace.flux_system: Creation complete after 0s [id=flux-system]
module.flux.kubectl_manifest.apply["a069a05f66424c71023f95eed5febd3957fc69d0"]: Creating...
module.flux.kubectl_manifest.apply["c852cde5c516e845113a8eb6bfeaef7b5fc75ebc"]: Creating...
module.flux.kubectl_manifest.apply["d0986d272da93888ff806ffa556e43d339dedc90"]: Creating...
module.flux.kubectl_manifest.apply["0c524fae3e35de368628eb33f6df79638d9ea647"]: Creating...
module.flux.kubectl_manifest.apply["a7ea28949988df7a7b9e81a536361f3301c9d6de"]: Creating...
module.flux.kubectl_manifest.apply["d83bbc3ad146b734e79a598df8b15de6395d4f53"]: Creating...
module.flux.kubectl_manifest.apply["6f052322541ad5a09b9b6650c1c294b4750084f9"]: Creating...
module.flux.kubectl_manifest.apply["884c0b9916fa8edd76faa855f15c76e56872bbb8"]: Creating...
module.flux.kubectl_manifest.apply["071e58bc56a89311d09561c8c51e127a0cb2fa74"]: Creating...
module.flux.kubectl_manifest.apply["e8dec72c727dacbbdd3ff43f86699007a310ace5"]: Creating...
module.flux.kubectl_manifest.apply["f35c3c068c03654beda357c604195581465fd5c3"]: Creating...
module.flux.kubectl_manifest.apply["2a1bd603c2a2d2e3d745a7b7e2e7ee6b0dcc56f6"]: Creating...
module.flux.kubectl_manifest.apply["56f5bbe5cf8070e59fbdabc5e2850b9813121c9b"]: Creating...
module.flux.kubectl_manifest.apply["85c5b3c8d4044db92ed3874c83b648c0aa931033"]: Creating...
module.flux.kubectl_manifest.apply["a8fb82dd0aaad503dadc8c60bd8667738dba480d"]: Creating...
module.flux.kubectl_manifest.apply["4bcde964f0eed0cfc1496ed03cac78993cc2ff0f"]: Creating...
module.flux.kubectl_manifest.apply["98f2a049dcfe3069f454e8bb406498c072f90f02"]: Creating...
module.flux.kubectl_manifest.apply["b080b75a041f756c93f07b42897700c396c7313d"]: Creating...
module.flux.kubectl_manifest.apply["24f077d6a715f446d96a7849f21fd3a6a2b54804"]: Creating...
module.flux.kubectl_manifest.apply["f7494ff36be81575b3af4a0a45e4df961d7d786a"]: Creating...
module.flux.kubectl_manifest.apply["d0547a4623c781f27e65c11bbef391ab7a00af04"]: Creating...
module.flux.kubectl_manifest.apply["cf65c44f6afcc1de18072b9443b6a0eb207901bf"]: Creating...
module.flux.kubectl_manifest.apply["6fd2e7a9df82bc886e733ed0a8febc1f765a6d70"]: Creating...
module.flux.kubectl_manifest.apply["6560c94ccc6349678ac86856a40a992cf2f489f3"]: Creating...
╷
│ Error: receivers.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["884c0b9916fa8edd76faa855f15c76e56872bbb8"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/helm-controller failed to create kubernetes rest client for update of resource: resource [v1/ServiceAccount] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["a8fb82dd0aaad503dadc8c60bd8667738dba480d"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/source-controller failed to create kubernetes rest client for update of resource: resource [apps/v1/Deployment] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["6f052322541ad5a09b9b6650c1c294b4750084f9"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/kustomize-controller failed to create kubernetes rest client for update of resource: resource [v1/ServiceAccount] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["56f5bbe5cf8070e59fbdabc5e2850b9813121c9b"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/source-controller failed to create kubernetes rest client for update of resource: resource [v1/Service] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["4bcde964f0eed0cfc1496ed03cac78993cc2ff0f"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: cluster-reconciler-flux-system failed to create kubernetes rest client for update of resource: resource [rbac.authorization.k8s.io/v1/ClusterRoleBinding] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["d0547a4623c781f27e65c11bbef391ab7a00af04"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system failed to create kubernetes rest client for update of resource: resource [v1/Namespace] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["cf65c44f6afcc1de18072b9443b6a0eb207901bf"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/notification-controller failed to create kubernetes rest client for update of resource: resource [v1/ServiceAccount] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["85c5b3c8d4044db92ed3874c83b648c0aa931033"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: crd-controller-flux-system failed to create kubernetes rest client for update of resource: resource [rbac.authorization.k8s.io/v1/ClusterRole] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["a7ea28949988df7a7b9e81a536361f3301c9d6de"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: alerts.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["2a1bd603c2a2d2e3d745a7b7e2e7ee6b0dcc56f6"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: helmcharts.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["d0986d272da93888ff806ffa556e43d339dedc90"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/notification-controller failed to create kubernetes rest client for update of resource: resource [apps/v1/Deployment] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["0c524fae3e35de368628eb33f6df79638d9ea647"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: providers.notification.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["98f2a049dcfe3069f454e8bb406498c072f90f02"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/helm-controller failed to create kubernetes rest client for update of resource: resource [apps/v1/Deployment] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["6560c94ccc6349678ac86856a40a992cf2f489f3"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: helmreleases.helm.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["071e58bc56a89311d09561c8c51e127a0cb2fa74"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: buckets.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["d83bbc3ad146b734e79a598df8b15de6395d4f53"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/source-controller failed to create kubernetes rest client for update of resource: resource [v1/ServiceAccount] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["6fd2e7a9df82bc886e733ed0a8febc1f765a6d70"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/kustomize-controller failed to create kubernetes rest client for update of resource: resource [apps/v1/Deployment] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["c852cde5c516e845113a8eb6bfeaef7b5fc75ebc"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/notification-controller failed to create kubernetes rest client for update of resource: resource [v1/Service] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["a069a05f66424c71023f95eed5febd3957fc69d0"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: helmrepositories.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["24f077d6a715f446d96a7849f21fd3a6a2b54804"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: kustomizations.kustomize.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["b080b75a041f756c93f07b42897700c396c7313d"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: gitrepositories.source.toolkit.fluxcd.io failed to create kubernetes rest client for update of resource: resource [apiextensions.k8s.io/v1/CustomResourceDefinition] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["e8dec72c727dacbbdd3ff43f86699007a310ace5"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: flux-system/webhook-receiver failed to create kubernetes rest client for update of resource: resource [v1/Service] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["f35c3c068c03654beda357c604195581465fd5c3"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {
│
╵
╷
│ Error: crd-controller-flux-system failed to create kubernetes rest client for update of resource: resource [rbac.authorization.k8s.io/v1/ClusterRoleBinding] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with module.flux.kubectl_manifest.apply["f7494ff36be81575b3af4a0a45e4df961d7d786a"],
│   on modules/flux/main.tf line 51, in resource "kubectl_manifest" "apply":
│   51: resource "kubectl_manifest" "apply" {

**Comment by jouros** [comment]
Again namespace gets created but nothing else: 
 kubectl get ns flux-system
NAME          STATUS   AGE
flux-system   Active   3m8s

**Comment by IbraheemAlSaady** [comment]
@jouros can you test the [basic](https://github.com/kube-champ/terraform-k8s-flux-bootstrap/tree/master/examples/basic) profile with the latest Minikube and see if it was working.

 If you have a public Github repo with all of your code, I can pull it and test it out myself

**Comment by jouros** [comment]
You have:
```yaml
provider "kubernetes" {
  config_path      = "~/.kube/config"
  # config_context   = "demo-cluster-admin"
}
```
In examples/basic/main.tf I did some testing with providers, simple yaml deployment with kubectl provider and if I use:
```yaml
 provider "kubectl" {
  config_path = "~/kubectl-config"
}
```
It works, If I do this:
```yaml
provider "kubernetes" {
  config_path = "~/kubectl-config"
}
```
It fails?
main.tf:
```yaml
provider "kubectl" {
  config_path = "~/kubectl-config"
}

#data "kubectl_server_version" "current" {
#}

resource "kubectl_manifest" "test" {
    yaml_body = <<YAML
apiVersion: v1
kind: Service
metadata:
  name: my-awesome-app-pod
  labels:
    app: my-awsome-app-pod
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
YAML
}
```

**Comment by jouros** [comment]
versions.tf in above test:
```yaml
terraform {
  required_version = ">=0.15"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.3.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "= 1.11.1"
    }
  }
}
```

**Comment by IbraheemAlSaady** [comment]
@jouros Is your `~/kubectl-config` file exist? and is it the correct file to authenticate to your cluster?

**Comment by jouros** [comment]
Yes, with provider kubectl service got deployed and with provider kubernetes it did not. Same kubectl-config in both.

**Comment by jouros** [comment]
Only line I changed in above test was first line: provider "kubernetes" or provider "kubectl". I'm not aware of relationship between kubernetes provider and kubectl provider, I just noticed that cube-config could be given to both of them.

**Comment by IbraheemAlSaady** [comment]
@jouros  I just tested your config with changing the path to my kubeconfig and it got deployed. (Tested with Minikube).

`kubectl` and `kubernetes` are two different terraform providers. `kubectl` is used in the [gavinbunney/kubectl provider](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) while Kubernetes is used in the [hashicorp/kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs).

Each provider has its own resources to create, the `resource "kubectl_manifest"` is created by the `gavinbunney/kubectl provider`, while the `resource "kubernetes_namespace" `is created by the `hashicorp/kubernetes`, they both require authenticating to the cluster by providing the following sections:

```terraform
provider "kubectl" {
  config_path = "~/kubectl-config"
}

provider "kubernetes" {
  config_path      = "~/kubectl-config"
  # config_context   = "demo-cluster-admin"
}
```

The module `terraform-k8s-flux-bootstrap` also uses the helm provider, which means you also need to provide the helm provider section

```terraform
provider "helm" { 
  kubernetes {    
     config_path = "~/kubectl-config"  
  }
}
```

Let me know if that works for you.

**Comment by jouros** [comment]
No, here flux-system namespace get created, so kubernetes provider get work done but all work for kubectl provider fail, I have tested with these:

main.tf:

```yaml
provider "kubectl" {
  config_path = "~/kubectl-config"
}

provider "helm" {
  kubernetes {
    config_path = "~/kubectl-config"
  }
}

data "flux_install" "main" {
  target_path        = var.flux_target_path
  network_policy     = var.flux_network_policy_enabled
  version            = var.flux_version
  namespace          = var.namespace
  registry           = var.registry
  image_pull_secrets = var.image_pull_secrets
  components         = toset(var.components)
  log_level          = var.log_level
}

data "flux_sync" "main" {
  target_path = var.flux_target_path
  url         = var.git_url
  branch      = var.git_branch
  interval    = var.sync_interval
  namespace   = var.namespace
}

data "kubectl_file_documents" "install" {
  content = data.flux_install.main.content
}

data "kubectl_file_documents" "sync" {
  content = data.flux_sync.main.content
}

resource "kubernetes_namespace" "flux_system" {
  metadata {
    name   = var.namespace
    labels = var.namespace_labels
  }

  lifecycle {
    ignore_changes = [
      metadata[0].labels,
    ]
  }
}

resource "kubectl_manifest" "apply" {
  for_each   = { for v in data.kubectl_file_documents.install.documents : sha1(v) => v }
  depends_on = [kubernetes_namespace.flux_system]

  yaml_body = each.value
}

# Apply manifests on the cluster
resource "kubectl_manifest" "sync" {
  for_each = { for v in data.kubectl_file_documents.sync.documents : sha1(v) => v }
  depends_on = [
    kubectl_manifest.apply,
    kubernetes_namespace.flux_system
  ]

  yaml_body = each.value
}
```

versions.tf:
```yaml
terraform {
  required_version = ">=0.15"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.3.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "= 1.11.1"
    }
    flux = {
      source  = "fluxcd/flux"
      version = "0.1.9"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.1.2"
    }
  }
}
```

main.tf:
```yaml
module "flux" {
  source                            = "./modules/flux"
  flux_target_path                  = var.flux_target_path
  flux_auth_type                    = var.flux_auth_type
  git_url                           = var.git_url
}
```

Also variables.tf from your example. I have no idea why kubectl_maifests fail here? This could be related to my K8s, but I need more accurate reason why this fails to open ticket for them.

**Comment by IbraheemAlSaady** [comment]
@jouros could be related to your cluster, that's why I'm suggesting testing with Minikube and reference the Minikube config file in the providers `config_map`. I tested it multiple times and it worked for me. If that works for you, then it's probably a cluster issue as you mentioned.

**Comment by jouros** [comment]
Yes, I'll do that, I have to setup different host for that test, so it will take day or two.

**Comment by IbraheemAlSaady** [comment]
I'll keep this issue open and wait for a confirmation from your side

**Comment by jouros** [comment]
Now I finally got this working: it seems that kubectl provider does not find kubeconfig if it's not here ~./kube/config. In all of my tests I have tried to use custom path and kubernetes provider has worked but kubectl did not work. Only change here in my test was to put kubeconfig into ~/.kube/config. 

This issue can be closed. 

Could you let me know do I have to install flux binary as it says in fluxcd.io/docs/installation => curl -s https://fluxcd.io/install.sh | sudo bash or is this deployment complete, so flux pipeline is working?

And thanks for your module, it is something I need.

**Comment by IbraheemAlSaady** [comment]
@jouros glad to hear that it's working for you and that it's something you need. You don't need to install the binary as the bootstrap and everything else happens with Terraform.

With this module, you only need to provide your git repo and the path for flux to pick up. After that, you need to add the public key to your git repo to authenticate Flux. You can provide your own keys, or use generated keys from the module

I'll close this issue. Please feel free to reach out if you need any help.
