### ISSUE TITLE
Bitbucket private key

### ISSUE THREAD

**Issue by Rajesh804** [kube-champ/terraform-k8s-flux-bootstrap#2]
Hi,

I am trying to use this with bitbucket and a private key like below:

module "flux-bootstrap" {
  source  = "kube-champ/flux-bootstrap/k8s"
  git_branch = "main"
  flux_auth_type    = "ssh"
  git_url           = "ssh://git@bitbucket.org/xxxxxx/xxxxxx.git"
  flux_target_path  = "clusters/demo_eks"
  flux_ssh_key = {
    auto_generate_key = false
    private_key       = "/Users/xxxxxx/Work/xxxxx/xxxxxxx.key"
  }
}

Could anyone please guide me with the correct code/snippet to work with bitbucket and its private key?

Thanks,
RR

**Comment by IbraheemAlSaady** [comment]
Hello @Rajesh804,

You need to use the `file` function by terraform to reference the file path: `private_key = file("/Users/xxxxxx/Work/xxxxx/xxxxxxx.key")`

You can have a look at the `custom-keys` example [here](https://github.com/kube-champ/terraform-k8s-flux-bootstrap/blob/master/examples/custom-keys/main.tf)
